name: Build Flatpak Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            cmake \
            curl \
            wget \
            git \
            flatpak \
            flatpak-builder \
            python3 \
            python3-pip \
            python3-setuptools \
            python3-wheel \
            libglib2.0-dev \
            libjson-glib-dev \
            libgtk-3-dev \
            meson \
            ninja-build

      - name: Setup Flatpak Builder Environment
        run: |
          git clone https://github.com/Twig6943/XeniaTest.git
          cd XeniaTest
          flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak update --appstream --assumeyes

      - name: Build Flatpak package
        run: |
          flatpak-builder --force-clean build-dir org.xenia.Canary.json

      - name: Bundle Flatpak app
        run: |
          flatpak build-bundle build-dir example.flatpak org.xenia.Canary --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo
