name: Build Flatpak Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flatpak Builder Environment
        run: |
          flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak update --appstream --assumeyes

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            cmake \
            curl \
            wget \
            git \
            python3 \
            python3-pip \
            python3-setuptools \
            python3-wheel \
            libglib2.0-dev \
            libjson-glib-dev \
            libgtk-3-dev \
            meson \
            ninja-build

      - name: Build Flatpak package
        run: |
          flatpak-builder --user --install --force-clean build-dir com.example.MyApp.yml
