name: Xenia CI

on:
  schedule:
    - cron: "0 0 */7 * *"
  push:
    branches: [ main ]
    paths-ignore: [ '**/README.md' ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ '**/README.md' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: artixlinux/artixlinux:latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            flatpak \
            git \
            build-essential \
            cmake \
            strace \
            patchelf \
            curl \
            wget \
            llvm \
            mesa \
            vulkan-tools \
            xorg-server-xvfb \
            libglib2.0-dev \
            python3 \
            python3-pip \
            python3-setuptools \
            python3-wheel

      - name: Install Flatpak SDK and Runtime
        run: |
          flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak install -y org.freedesktop.Sdk//23.08 org.freedesktop.Platform//23.08

      - name: Build Flatpak package
        run: |
          mkdir -p xenia-flatpak
          cd xenia-flatpak
          
          # Initialize Flatpak manifest
          echo '{
            "app-id": "org.xenia.Canary",
            "runtime": "org.freedesktop.Platform",
            "runtime-version": "23.08",
            "sdk": "org.freedesktop.Sdk",
            "command": "xenia-canary",
            "modules": [
              {
                "name": "xenia-canary",
                "buildsystem": "simple",
                "build-commands": [
                  "git clone --recursive --branch canary_experimental https://github.com/xenia-canary/xenia-canary.git",
                  "cd xenia-canary && python3 xenia-build setup --target_os=linux",
                  "python3 xb premake --cc gcc",
                  "python3 xb build --config=release",
                  "install -Dm755 build/bin/Linux/Release/xenia-canary \$FLATPAK_DEST/bin/xenia-canary",
                  "install -Dm644 assets/icon/256.png \$FLATPAK_DEST/share/icons/hicolor/256x256/apps/xenia.png",
                  "install -Dm644 org.xenia.Canary.desktop \$FLATPAK_DEST/share/applications/org.xenia.Canary.desktop"
                ],
                "sources": [
                  {
                    "type": "git",
                    "url": "https://github.com/xenia-canary/xenia-canary.git",
                    "branch": "canary_experimental"
                  },
                  {
                    "type": "file",
                    "url": "https://github.com/xenia-project/xenia/blob/master/assets/icon/256.png?raw=true",
                    "dest-filename": "xenia.png",
                    "sha256": "a1686a9d50baad70a5658e0a2cb38a34f7c96fa41f5beebb81bcf405355b712f"
                  },
                  {
                    "type": "file",
                    "path": "org.xenia.Canary.desktop"
                  }
                ]
              }
            ]
          }' > xenia-canary.json

          # Build the Flatpak
          flatpak-builder --repo=xenia-repo --force-clean --arch x86_64 build xenia-canary.json

      - name: Check version file
        run: |
          cat ~/version
          echo "APP_VERSION=$(cat ~/version)" >> "${GITHUB_ENV}"
      
      - name: Upload Flatpak artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: Flatpak
          path: 'xenia-repo'

  release:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4.1.8
        with:
          name: Flatpak

      - name: Read version
        run: |
          cat version
          export VERSION="$(<version)"
          echo "APP_VERSION=${VERSION}" >> "${GITHUB_ENV}"

      - name: Create release
        run: |
          gh release create "${APP_VERSION}" --repo "${GITHUB_REPOSITORY}" --generate-notes --title "Release ${{ env.APP_VERSION }}" xenia-repo/*.flatpak
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
